config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :games
  get '/history', to: 'games#history'
  get '/log', to: 'games#new'
  root 	to: 'home#index'
end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :user
	belongs_to :opponent, class_name: 'User'

	after_initialize :set_defaults
	before_save :game_rules
	after_create :update_rankings

	scope :games_played, ->(user_id) { where("user_id = ? OR opponent_id = ?", user_id, user_id) }

	validates_presence_of :user_id, :opponent_id
	validate :winner

	def winner
		if user_score > opponent_score
			self.result = true
		end

	end

	def game_rules
		if user_score >= 21 || opponent_score >= 21
			result = user_score - opponent_score
			return true if result.abs >= 2
		end

		errors.add(:base, "To win, one must get 21 or more points with a minimun difference of 2.")
		return false
	end

	def update_rankings
		self.user.update_rankings self
	end

	def set_defaults
		self.result ||= false
		self.user_score ||= 0
		self.opponent_score ||= 0
		self.game_date ||= Date.today
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	include Elo

	after_initialize :set_defaults

	devise :database_authenticatable, :registerable, :trackable, :validatable

	scope :play_against, ->(user_id) { where.not(id: user_id) }

	def just_name
		self.email.split("@").first.capitalize
	end

	def games_played
		Game.games_played(id)
	end

	def play_against
		User.play_against(id)
	end

	def set_defaults
		self.ranking ||= 2000
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/concerns/elo.rb
module Elo
	extend ActiveSupport::Concern

	def update_rankings game
		rankings = new_rankings(self.ranking, game.opponent.ranking, game.result ? 1:0)

		self.update ranking: rankings['player1']
		game.opponent.update ranking: rankings['player2']
	end

	def new_rankings(player1_ranking,player2_ranking,result,k_value=32,should_round=true)
		#Assign actual individual results
		player1_result = result
		player2_result = 1 - result

		#Calculate expected results
		player1_expectation = 1/(1+10**((player2_ranking - player1_ranking)/400.0)) #the .0 is important to force float operations!))
		player2_expectation = 1/(1+10**((player1_ranking - player2_ranking)/400.0))

		#Calculate new rankings
		player1_new_ranking = player1_ranking + (k_value*(player1_result - player1_expectation))
		player2_new_ranking = player2_ranking + (k_value*(player2_result - player2_expectation))

		#Optional rounding
		if should_round
		  # int rounds down and forces type
		  player1_new_ranking = player1_new_ranking.round
		  player2_new_ranking = player2_new_ranking.round
		end 
		
		# Create a dictionary to return and do so!
		new_rankings_hash = Hash.new
		new_rankings_hash['player1'] = player1_new_ranking
		new_rankings_hash['player2'] = player2_new_ranking
		
		new_rankings_hash
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/history
  def history
    @games = current_user.games_played
  end

  # GET /games/1
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  def create
    @game = Game.new(game_params)
    @game.user_id = current_user.id

    if @game.save
      redirect_to history_path, notice: 'Game was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /games/1
  def update
    if @game.update(game_params)
      redirect_to @game, notice: 'Game was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    redirect_to games_url, notice: 'Game was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def game_params
      params.require(:game).permit(:user_id, :opponent_id, :user_score, :opponent_score, :game_date, :result)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@users = User.order(ranking: :desc)
  end

  def history
  	redirect_to games_history_path
  end

  def log
  	redirect_to new_game_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
	def opponent_name(game)
		if(current_user == game.user)
			game.opponent.just_name
		else
			game.user.just_name
		end
	end

	def result_to_s(game)
		if(current_user == game.user)
			game.result ? 'W' : 'L'
		else
			game.result ? 'L' : 'W'
		end
	end

	def score_to_s(game)
		if(current_user == game.user)
			"#{game.user_score}-#{game.opponent_score}"
		else
			"#{game.opponent_score}-#{game.user_score}"
		end
	end
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :game_date, 'Date Played' %><br>
    <%= f.date_select :game_date %>
  </div>
  <div class='input-group'>
    <%= f.label :opponent_id %><br>
    <%= f.collection_select :opponent_id, current_user.play_against, :id, :just_name, {}, class: 'form-control' %>
  </div>
  <div class='input-group'>
    <%= f.label :user_score, 'Your Score' %><br>
    <%= f.number_field :user_score, class: 'form-control' %>
  </div>
  <div class='input-group'>
    <%= f.label :opponent_score, 'Their Score' %><br>
    <%= f.number_field :opponent_score, class: 'form-control' %>
  </div> 
  <br>
  <div class='actions'>
    <%= f.submit 'Save' %>
  </div>

<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/history.html.erb
<p id="notice"><%= notice %></p>

<h1 class='page-header'>History</h1>

<div class="container">        
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Opponent</th>
        <th>Score</th>
        <th>Result</th>
      </tr>
    </thead>
    <tbody>
	<% @games.each_with_index do |game| %>
		<tr>
			<td><%= game.game_date  %></td>
			<td><%= opponent_name(game) %></td>
	        <td><%= score_to_s(game) %></td>
	        <td><%= result_to_s(game) %></td>
	    </tr>
	<% end %>
    </tbody>
  </table>
</div>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leaderboards</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Opponent</th>
      <th>User score</th>
      <th>Opponent score</th>
      <th>Game date</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.user_id %></td>
        <td><%= game.opponent_id %></td>
        <td><%= game.user_score %></td>
        <td><%= game.opponent_score %></td>
        <td><%= game.game_date %></td>
        <td><%= game.result %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1 class='page-header'>Log Game</h1>

<%= render 'form' %>

<%= link_to 'cancel', root_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @game.user_id %>
</p>

<p>
  <strong>Opponent:</strong>
  <%= @game.opponent_id %>
</p>

<p>
  <strong>User score:</strong>
  <%= @game.user_score %>
</p>

<p>
  <strong>Opponent score:</strong>
  <%= @game.opponent_score %>
</p>

<p>
  <strong>Game date:</strong>
  <%= @game.game_date %>
</p>

<p>
  <strong>Result:</strong>
  <%= @game.result %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/home/history.html.erb
<h1 class='page-header'>History</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('history.png') %>

app/views/home/index.html.erb
<h1 class='page-header'>Leaderboard</h1>

<div class="container">        
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Rank</th>
        <th>Name</th>
        <th>Score</th>
        <th>Games Played</th>
      </tr>
    </thead>
    <tbody>
    	<% @users.each_with_index do |user, index| %>
    		<tr>
    			<td><%= index+1 %></td>
    			<td><%= user.just_name %></td>
		        <td><%= user.ranking %></td>
		        <td><%= user.games_played.count %></td>
		    </tr>
    	<% end %>
    </tbody>
  </table>
</div>

app/views/home/log.html.erb
<h1 class='page-header'>Log Game</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('log_game.png') %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pingpong</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= link_to 'Log Game', '/log', class: 'btn btn-success navbar-btn' %>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Leadboard', root_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href="/history">History</a></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pingpong Leaderboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
    <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'layouts/header' %>

    <div class='container'>
      <%= yield %>
    </div>
    
  </body>
</html>